# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:12.6.0

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm test
          - pipe: snyk/snyk-scan:0.2.0
            variables:
              SNYK_TOKEN: '$SNYK_API_TOKEN'
              LANGUAGE: 'npm'
              # IMAGE_NAME: '<string>' # Only required if LANGUAGE set to 'docker'
              DONT_BREAK_BUILD: 'true' # Optional.
              MONITOR: 'true' # Optional.
              # SEVERITY_THRESHOLD: '<low|medium|high>' # Optional.
              ORGANIZATION: '$SNYK_ORG_ID' # Optional.
              # PROJECT_FOLDER: '<string>' # Optional.
              # TARGET_FILE: '<string>' # Optional.
              # EXTRA_ARGS: '<string>' # Optional.
              # DEBUG: '<boolean>' # Optional.
